#-------------------------------
# General Site Settings

title: Finplace
logo: 
author: FinPlace
description: Encuentra tu partner financiero
email: finplacegroup@gmail.com
phone: +569 7888 6663
#address: 125/A, CA Commercial Area, California, USA
#copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: ¿Eres Contador?, link: 'https://forms.gle/Ba84h99N9P3KYiME8'}
#- {name: Blog, link: '/finplace/blog'}
#- {name: Portfolio, link: '/finplace/portfolio'}
#- {name: Contact, link: '/finplace/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Encuentra <br> tu contador <br> ideal

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Llena el formulario para conocerte y recomendarte los mejores contadores para tu industria y problemática. Si no se cumplen tus requisitos de satisfacción se te devuolverá el dinero.
 
blurb-btn-link: 'https://forms.gle/3ty4UH8gEWEuAggA7'
blurb-btn-name: Empezar



#-------------------------------
# Contact Section

contact-title: Contacto
contact-email: finplacegroup@gmail.com
